# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: rm -rf node_modules
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - deploy:
          name: Deploy staging
          filters: 
            tags: 
              ignore: 
                /.*/
            branches: 
              only: /sc-112/ # Just to test, revert to /^master$/
          command: |
            ./scripts/prepare_build.sh && \
              ./scripts/cf_staging.sh && \
              cf zero-downtime-push smart-cities-staging -f manifest.yml -p build
      - deploy: 
          name: Deploy prod
          filters: 
            branches: 
              ignore: 
                /.*/
            tags: 
              only: 
                /^release-.*/
          command: |
            ./scripts/prepare_build.sh && \
              ./scripts/cf_production.sh && \
              cf zero-downtime-push smart-cities -f manifest.yml -p build
