# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: rm -rf node_modules
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test: 
    docker: 
      - image: circleci/node:8.1.2
    working_directory: ~/repo
    steps:
      - run: npm test
  deploy_staging: 
    docker: 
      - image: circleci/node:8.1.2      
    working_directory: ~/repo
    steps:
      - run: ./scripts/prepare_build.sh
      - run: ./scripts/cf_staging.sh
      - run: cf zero-downtime-push smart-cities-staging -f manifest.yml -p build
  deploy_production: 
    docker: 
      - image: circleci/node:8.1.2      
    working_directory: ~/repo
    steps:
      - run: ./scripts/prepare_build.sh
      - run: ./scripts/cf_production.sh
      - run: cf zero-downtime-push smart-cities -f manifest.yml -p build
workflows: 
  version: 2
  build_test_deploy:
    jobs: 
      - build
      - test: 
        requires: 
          - build
      - deploy_staging: 
        requires: 
          - test
        filters: 
          tags: 
            ignore: 
              /.*/
          branches: 
            only: /^master$/
      - deploy_production:
        requires: 
          - test
        filters: 
          branches: 
            ignore: 
              /.*/
          tags: 
            only: 
              /^release-.*/
